version: '3.8'

services:
  vapi-simli-drive-thru:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      # VAPI Configuration
      - NEXT_PUBLIC_VAPI_PUBLIC_KEY=${NEXT_PUBLIC_VAPI_PUBLIC_KEY}
      - VAPI_PRIVATE_KEY=${VAPI_PRIVATE_KEY}
      - NEXT_PUBLIC_VAPI_ASSISTANT_ID=${NEXT_PUBLIC_VAPI_ASSISTANT_ID}
      
      # Simli Configuration  
      - NEXT_PUBLIC_SIMLI_API_KEY=${NEXT_PUBLIC_SIMLI_API_KEY}
      - NEXT_PUBLIC_SIMLI_FACE_ID=${NEXT_PUBLIC_SIMLI_FACE_ID}
      
      # Server Configuration
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - NODE_ENV=production
      
    volumes:
      - app-data:/app
    command: >
      sh -c "
        if [ ! -f package.json ]; then
          echo '🚀 First time setup - cloning repository...'
          apk add --no-cache git &&
          git clone https://github.com/faustosip/vapi-simli-drive-thru.git . &&
          npm install &&
          npm run build
        fi &&
        echo '✅ Starting application...' &&
        npm start
      "
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - vapi-network

volumes:
  app-data:
    driver: local

networks:
  vapi-network:
    driver: overlay
    attachable: true